export const FETCH_MESSAGE_LIST = 'MESSAGE/FETCH_MESSAGE_LIST'
export const FETCH_MESSAGE_LIST_SUCESS = 'MESSAGE/FETCH_MESSAGE_LIST_SUCESS'
export const FETCH_MESSAGE_LIST_FAIL = 'MESSAGE/FETCH_MESSAGE_LIST_FAIL'