export const FETCH_MESSAGE_LIST = 'MESSAGE/FETCH_MESSAGE_LIST'
export const FETCH_MESSAGE_LIST_SUCCESS = 'MESSAGE/FETCH_MESSAGE_LIST_SUCCESS'
export const FETCH_MESSAGE_LIST_FAIL = 'MESSAGE/FETCH_MESSAGE_LIST_FAIL'