export const FETCH_MESSAGE_LIST = 'MESSAGE/FETCH_MESSAGE_LIST'
export const FETCH_MESSAGE_LIST_SUCCESS = 'MESSAGE/FETCH_MESSAGE_LIST_SUCCESS'
export const FETCH_MESSAGE_LIST_FAIL = 'MESSAGE/FETCH_MESSAGE_LIST_FAIL'

export const REMOVE_MESSAGE_WITH_ID = 'MESAAGE/REMOVE_MESSAGE_WITH_ID'

export const INCREASE_UNREAD_COUNT = 'MESAAGE/INCREASE_UNREAD_COUNT'

